/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.company.resume.panel;

import com.company.dao.impl.EmploymentHistoryDaoImpl;
import com.company.dao.inter.EmploymentHistoryDaoInter;
import com.company.entity.EmploymentHistory;
import com.company.main.Context;
import com.company.resume.config.Config;
import java.sql.Date;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Seymur
 */
public class PanelEmploymentHistory extends javax.swing.JPanel {

    private EmploymentHistoryDaoInter employmentHistory = Context.instanceEmploymentHistoryDao();
    private SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");

    /**
     * Creates new form EmploymentHistory
     */
    public PanelEmploymentHistory() {
        initComponents();
    }

    public void fillUserComponents() {
        EmploymentHistory emp = new EmploymentHistory();
        List<EmploymentHistory> list = employmentHistory.getAllEmploymentHistoryByUserId(7);
        System.out.println("list = "+list);
        list.add(emp);
        txtHeader.setText(emp.getHeader());
        txtJobDesc.setText(emp.getJobDescription());

        Date date = emp.getBeginDate();

        String dateBegin = sdf.format(date);
        txtBeginDate.setText(dateBegin);

        String dateEnd = sdf.format(date);
        txtEndDate.setText(dateEnd);

    }

    public void fillHistory(EmploymentHistory emp) {
        try {
            String header = txtHeader.getText();
            String jobDesc = txtJobDesc.getText();

            String beginDate = txtBeginDate.getText();
            String endDate = txtEndDate.getText();

            java.util.Date begin = sdf.parse(beginDate);
            java.util.Date end = sdf.parse(endDate);

            java.sql.Date bd = new java.sql.Date(begin.getTime());
            java.sql.Date ed = new java.sql.Date(end.getTime());

            emp.setHeader(header);
            emp.setJobDescription(jobDesc);
            emp.setBeginDate(bd);
            emp.setEndDate(ed);

        } catch (ParseException ex) {
            Logger.getLogger(PanelEmploymentHistory.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlEmploymentHistory = new javax.swing.JPanel();
        lblHeader = new javax.swing.JLabel();
        txtHeader = new javax.swing.JTextField();
        lblBeginDate = new javax.swing.JLabel();
        txtBeginDate = new javax.swing.JTextField();
        lblEndDate = new javax.swing.JLabel();
        txtEndDate = new javax.swing.JTextField();
        lblJobDesc = new javax.swing.JLabel();
        txtJobDesc = new javax.swing.JTextField();

        lblHeader.setText("Header:");

        txtHeader.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHeaderActionPerformed(evt);
            }
        });

        lblBeginDate.setText("Begin Date:");

        lblEndDate.setText("End Date:");

        lblJobDesc.setText("Job Description:");

        javax.swing.GroupLayout pnlEmploymentHistoryLayout = new javax.swing.GroupLayout(pnlEmploymentHistory);
        pnlEmploymentHistory.setLayout(pnlEmploymentHistoryLayout);
        pnlEmploymentHistoryLayout.setHorizontalGroup(
            pnlEmploymentHistoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlEmploymentHistoryLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(pnlEmploymentHistoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblHeader)
                    .addComponent(lblBeginDate)
                    .addComponent(lblEndDate)
                    .addComponent(lblJobDesc))
                .addGap(52, 52, 52)
                .addGroup(pnlEmploymentHistoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtHeader)
                    .addComponent(txtBeginDate)
                    .addComponent(txtEndDate, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE)
                    .addComponent(txtJobDesc))
                .addContainerGap(339, Short.MAX_VALUE))
        );
        pnlEmploymentHistoryLayout.setVerticalGroup(
            pnlEmploymentHistoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlEmploymentHistoryLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(pnlEmploymentHistoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblHeader)
                    .addComponent(txtHeader, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(pnlEmploymentHistoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBeginDate)
                    .addComponent(txtBeginDate, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addGroup(pnlEmploymentHistoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEndDate)
                    .addComponent(txtEndDate, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(pnlEmploymentHistoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblJobDesc)
                    .addComponent(txtJobDesc, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(255, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlEmploymentHistory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlEmploymentHistory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtHeaderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHeaderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHeaderActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblBeginDate;
    private javax.swing.JLabel lblEndDate;
    private javax.swing.JLabel lblHeader;
    private javax.swing.JLabel lblJobDesc;
    private javax.swing.JPanel pnlEmploymentHistory;
    private javax.swing.JTextField txtBeginDate;
    private javax.swing.JTextField txtEndDate;
    private javax.swing.JTextField txtHeader;
    private javax.swing.JTextField txtJobDesc;
    // End of variables declaration//GEN-END:variables
}
